name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build ${{ matrix.os }} ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.5", "3.6", "3.7", "3.8", "3.9", "3.10"]
        include:
        - os: windows-latest
          python-version: "3.10"
        - os: macos-latest
          python-version: "3.10"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install requests click python-dateutil sentinelsat>=1.0 pytest responses
    - name: Test with pytest
      run: |
        python -m pytest -v -W=error
